CREATE TABLE IF NOT EXISTS access_tokens (
  id SERIAL PRIMARY KEY,
  service_name VARCHAR(50) NOT NULL,
  token TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(service_name)
); 