api:
  productHunt:
    baseUrl: https://api.producthunt.com/v2
    graphqlUrl: https://api.producthunt.com/v2/api/graphql
    oauthUrl: https://api.producthunt.com/v2/oauth/authorize
    tokenUrl: https://api.producthunt.com/v2/oauth/token
    redirectUri: https://producthunt-sdk.vercel.app/callback
    serviceName: producthunt
    scopes:
      - public
      - private

database:
  tableName: access_tokens 